import type { DegreeTemplate } from './types';

export const SOLAR_DEGREES: DegreeTemplate[] = [
  {
    degree: 0,
    name: 'Solar: Seedwheel',
    sigilFamily: ['seedOfLife', 'sunWheel'],
    ornament: ['triSpokes', 'petalNodes'],
    motion: ['rotateSlow', 'pulseWarm'],
    abilityBias: { tap: 1.2, hold: 1.0, fastSwipe: 0.6 },
    ruleBias: { mirrorThresholdDelta: -2, mutationRateDelta: 1 },
  },
  {
    degree: 1,
    name: 'Solar: Dawn Spiral',
    sigilFamily: ['goldenSpiral', 'fibonacciArc'],
    ornament: ['sunMotes', 'spiralBeads'],
    motion: ['spiralDrift', 'breathe'],
    abilityBias: { trace: 1.1, hold: 1.0, tap: 0.8 },
    ruleBias: { aestheticDriftDelta: 1 },
  },
  {
    degree: 2,
    name: 'Solar: Radiant Petals',
    sigilFamily: ['flowerOfLife', 'sunPetals'],
    ornament: ['petalNodes', 'haloRing'],
    motion: ['pulseWarm', 'expandContract'],
    abilityBias: { tap: 1.3, slowSwipe: 0.8 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 3,
    name: 'Solar: Temple Gate',
    sigilFamily: ['squareCircle', 'templeFrame'],
    ornament: ['cornerRunes', 'sunShield'],
    motion: ['steadyGlow', 'pulseWarm'],
    abilityBias: { hold: 1.2, tap: 0.9 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 4,
    name: 'Solar: Trispoke Crown',
    sigilFamily: ['triSpokes', 'haloCrown'],
    ornament: ['crownBeads', 'sunMotes'],
    motion: ['rotateMedium', 'pulseWarm'],
    abilityBias: { tap: 1.0, doubleTap: 1.0 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 5,
    name: 'Solar: Ember Choir',
    sigilFamily: ['sunWheel', 'emberRing'],
    ornament: ['emberSparks', 'glyphFlies'],
    motion: ['sparkBurst', 'breathe'],
    abilityBias: { rhythm: 1.3, tap: 1.0 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 6,
    name: 'Solar: Halo Lattice',
    sigilFamily: ['metatronSoft', 'haloRing'],
    ornament: ['latticeDots', 'goldPollen'],
    motion: ['rotateSlow', 'shimmer'],
    abilityBias: { hold: 1.1, trace: 1.0 },
    ruleBias: { mirrorThresholdDelta: -2 },
  },
  {
    degree: 7,
    name: 'Solar: Lion Sigil',
    sigilFamily: ['sunPetals', 'guardianMark'],
    ornament: ['teethTriangles', 'glowLines'],
    motion: ['pulseWarm', 'snapBright'],
    abilityBias: { fastSwipe: 1.2, tap: 1.0 },
    ruleBias: { mirrorThresholdDelta: 1 },
  },
  {
    degree: 8,
    name: 'Solar: Sunshield',
    sigilFamily: ['sunShield', 'squareCircle'],
    ornament: ['gateRunes', 'orbitDots'],
    motion: ['steadyGlow', 'shieldPulse'],
    abilityBias: { hold: 1.3, tap: 1.0 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 9,
    name: 'Solar: Golden Lotus',
    sigilFamily: ['flowerOfLife', 'lotusMandala'],
    ornament: ['petalNodes', 'softBeads'],
    motion: ['breathe', 'pulseWarm'],
    abilityBias: { slowSwipe: 1.0, tap: 1.1 },
    ruleBias: { mutationRateDelta: -1 },
  },
  {
    degree: 10,
    name: 'Solar: Spiral Forge',
    sigilFamily: ['goldenSpiral', 'sunWheel'],
    ornament: ['hammerRunes', 'emberSparks'],
    motion: ['rotateMedium', 'sparkBurst'],
    abilityBias: { trace: 1.2, fastSwipe: 0.9 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 11,
    name: 'Solar: Aurora Bloom',
    sigilFamily: ['vesicaBloom', 'haloRing'],
    ornament: ['petalGlints', 'softRays'],
    motion: ['shimmer', 'expandContract'],
    abilityBias: { tap: 1.0, hold: 1.0, slowSwipe: 1.0 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 12,
    name: 'Solar: Chariot Lines',
    sigilFamily: ['squareCircle', 'sunWheel'],
    ornament: ['lineGrid', 'cornerRunes'],
    motion: ['rotateSlow', 'steadyGlow'],
    abilityBias: { hold: 1.1, fastSwipe: 1.0 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 13,
    name: 'Solar: Scarab Seal',
    sigilFamily: ['metatronSoft', 'guardianMark'],
    ornament: ['beetleGem', 'goldPollen'],
    motion: ['shimmer', 'pulseWarm'],
    abilityBias: { doubleTap: 1.1, tap: 1.0 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 14,
    name: 'Solar: Noon Radiance',
    sigilFamily: ['sunPetals', 'haloRing'],
    ornament: ['hardRays', 'orbitDots'],
    motion: ['snapBright', 'pulseWarm'],
    abilityBias: { tap: 1.2, fastSwipe: 1.1 },
    ruleBias: { mirrorThresholdDelta: 2 },
  },
  {
    degree: 15,
    name: 'Solar: Hearth Rune',
    sigilFamily: ['seedOfLife', 'templeFrame'],
    ornament: ['glyphFlies', 'emberSparks'],
    motion: ['breathe', 'steadyGlow'],
    abilityBias: { hold: 1.2, rhythm: 1.0 },
    ruleBias: { mutationRateDelta: -1 },
  },
  {
    degree: 16,
    name: 'Solar: Crown of Rings',
    sigilFamily: ['haloCrown', 'sunWheel'],
    ornament: ['crownBeads', 'triSpokes'],
    motion: ['rotateMedium', 'rotateSlow'],
    abilityBias: { doubleTap: 1.0, tap: 1.0, hold: 1.0 },
    ruleBias: { aestheticDriftDelta: 1 },
  },
  {
    degree: 17,
    name: 'Solar: Radiant Geometry',
    sigilFamily: ['metatronSoft', 'squareCircle'],
    ornament: ['latticeDots', 'hardRays'],
    motion: ['rotateSlow', 'pulseWarm'],
    abilityBias: { trace: 1.0, tap: 1.1 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 18,
    name: 'Solar: Ember Veil',
    sigilFamily: ['emberRing', 'vesicaBloom'],
    ornament: ['emberSparks', 'petalGlints'],
    motion: ['sparkBurst', 'shimmer'],
    abilityBias: { fastSwipe: 1.0, tap: 1.0 },
    ruleBias: { mirrorThresholdDelta: 1 },
  },
  {
    degree: 19,
    name: 'Solar: Zenith Seal',
    sigilFamily: ['sunShield', 'haloRing'],
    ornament: ['gateRunes', 'hardRays'],
    motion: ['steadyGlow', 'snapBright'],
    abilityBias: { hold: 1.3, tap: 1.0 },
    ruleBias: { mirrorThresholdDelta: 3, mutationRateDelta: 1 },
  },
];

export const LUNAR_DEGREES: DegreeTemplate[] = [
  {
    degree: 20,
    name: 'Lunar: Crescent Gate',
    sigilFamily: ['crescentRing', 'vesica'],
    ornament: ['starPoints', 'pearlBeads'],
    motion: ['breathe', 'shimmer'],
    abilityBias: { slowSwipe: 1.2, hold: 1.0 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 21,
    name: 'Lunar: Star Net',
    sigilFamily: ['constellationGrid', 'flowerSoft'],
    ornament: ['starLines', 'mistBeads'],
    motion: ['drift', 'connectPulse'],
    abilityBias: { trace: 1.2, slowSwipe: 1.0 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 22,
    name: 'Lunar: Dream Spiral',
    sigilFamily: ['goldenSpiralCool', 'moonRing'],
    ornament: ['moonDust', 'softBeads'],
    motion: ['spiralDrift', 'breathe'],
    abilityBias: { slowSwipe: 1.1, trace: 1.0 },
    ruleBias: { aestheticDriftDelta: 1 },
  },
  {
    degree: 23,
    name: 'Lunar: Tide Mandala',
    sigilFamily: ['tideRings', 'vesica'],
    ornament: ['waveLines', 'mistBeads'],
    motion: ['wavePulse', 'breathe'],
    abilityBias: { slowSwipe: 1.3 },
    ruleBias: { mutationRateDelta: -1 },
  },
  {
    degree: 24,
    name: 'Lunar: Pearl Halo',
    sigilFamily: ['pearlRing', 'moonRing'],
    ornament: ['pearlBeads', 'starPoints'],
    motion: ['shimmer', 'rotateSlow'],
    abilityBias: { hold: 1.2, tap: 0.8 },
    ruleBias: { mirrorThresholdDelta: -2 },
  },
  {
    degree: 25,
    name: 'Lunar: Archivist Grid',
    sigilFamily: ['constellationGrid', 'squareCircleSoft'],
    ornament: ['cornerRunes', 'starLines'],
    motion: ['steadyGlow', 'connectPulse'],
    abilityBias: { trace: 1.3 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 26,
    name: 'Lunar: Owl Sigil',
    sigilFamily: ['moonRing', 'guardianMarkSoft'],
    ornament: ['featherGlints', 'starPoints'],
    motion: ['blinkGlow', 'drift'],
    abilityBias: { tap: 1.0, slowSwipe: 1.0 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 27,
    name: 'Lunar: Mist Veil',
    sigilFamily: ['mistLens', 'vesica'],
    ornament: ['mistBeads', 'moonDust'],
    motion: ['drift', 'breathe'],
    abilityBias: { hold: 1.1, slowSwipe: 1.2 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 28,
    name: 'Lunar: Seven Stars',
    sigilFamily: ['sevenStarCrown', 'moonRing'],
    ornament: ['starPoints', 'starLines'],
    motion: ['connectPulse', 'rotateSlow'],
    abilityBias: { trace: 1.1, tap: 1.0 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 29,
    name: 'Lunar: Constellation Bloom',
    sigilFamily: ['flowerSoft', 'constellationGrid'],
    ornament: ['petalNodes', 'starPoints'],
    motion: ['pulseCool', 'connectPulse'],
    abilityBias: { tap: 1.1, trace: 1.0 },
    ruleBias: { mirrorThresholdDelta: 1 },
  },
  {
    degree: 30,
    name: 'Lunar: Dream Archive',
    sigilFamily: ['squareCircleSoft', 'moonRing'],
    ornament: ['cornerRunes', 'pearlBeads'],
    motion: ['steadyGlow', 'breathe'],
    abilityBias: { hold: 1.2, trace: 1.0 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 31,
    name: 'Lunar: Moth Lantern',
    sigilFamily: ['crescentRing', 'haloCrownSoft'],
    ornament: ['featherGlints', 'moonDust'],
    motion: ['shimmer', 'blinkGlow'],
    abilityBias: { tap: 1.0, doubleTap: 1.0 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 32,
    name: 'Lunar: Tidal Eye',
    sigilFamily: ['tideRings', 'eyeLens'],
    ornament: ['waveLines', 'starPoints'],
    motion: ['wavePulse', 'pulseCool'],
    abilityBias: { slowSwipe: 1.2, hold: 1.0 },
    ruleBias: { mirrorThresholdDelta: 2 },
  },
  {
    degree: 33,
    name: 'Lunar: Silver Weave',
    sigilFamily: ['vesica', 'constellationGrid'],
    ornament: ['weaveLines', 'pearlBeads'],
    motion: ['drift', 'connectPulse'],
    abilityBias: { trace: 1.2, slowSwipe: 1.0 },
    ruleBias: { aestheticDriftDelta: 1 },
  },
  {
    degree: 34,
    name: 'Lunar: Moonlit Spiral',
    sigilFamily: ['goldenSpiralCool', 'crescentRing'],
    ornament: ['moonDust', 'starLines'],
    motion: ['spiralDrift', 'drift'],
    abilityBias: { slowSwipe: 1.1, fastSwipe: 0.7 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 35,
    name: 'Lunar: Whale Song',
    sigilFamily: ['tideRings', 'flowerSoft'],
    ornament: ['waveLines', 'mistBeads'],
    motion: ['wavePulse', 'breathe'],
    abilityBias: { rhythm: 1.2, slowSwipe: 1.0 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 36,
    name: 'Lunar: Night Map',
    sigilFamily: ['constellationGrid', 'sevenStarCrown'],
    ornament: ['starLines', 'cornerRunes'],
    motion: ['connectPulse', 'steadyGlow'],
    abilityBias: { trace: 1.3 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 37,
    name: 'Lunar: Pearl Crown',
    sigilFamily: ['haloCrownSoft', 'pearlRing'],
    ornament: ['pearlBeads', 'starPoints'],
    motion: ['rotateSlow', 'shimmer'],
    abilityBias: { hold: 1.2 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 38,
    name: 'Lunar: Mist Archive',
    sigilFamily: ['mistLens', 'squareCircleSoft'],
    ornament: ['cornerRunes', 'mistBeads'],
    motion: ['drift', 'steadyGlow'],
    abilityBias: { hold: 1.1, trace: 1.1 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 39,
    name: 'Lunar: Full Moon Seal',
    sigilFamily: ['moonRing', 'pearlRing'],
    ornament: ['starPoints', 'softBeads'],
    motion: ['pulseCool', 'shimmer'],
    abilityBias: { tap: 1.0, hold: 1.2 },
    ruleBias: { mirrorThresholdDelta: 3 },
  },
];

export const VOID_DEGREES: DegreeTemplate[] = [
  {
    degree: 40,
    name: 'Void: Fracture Ring',
    sigilFamily: ['fractureCircle', 'metatronShard'],
    ornament: ['shardDust', 'glitchPixels'],
    motion: ['flicker', 'shiver'],
    abilityBias: { doubleTap: 1.3, fastSwipe: 1.0 },
    ruleBias: { mutationRateDelta: 2 },
  },
  {
    degree: 41,
    name: 'Void: Abyss Spiral',
    sigilFamily: ['voidSpiral', 'fractureCircle'],
    ornament: ['inkDrops', 'prismNoise'],
    motion: ['pullIn', 'spiralDrift'],
    abilityBias: { hold: 1.2, trace: 1.0 },
    ruleBias: { mirrorThresholdDelta: 2 },
  },
  {
    degree: 42,
    name: 'Void: Glitch Crown',
    sigilFamily: ['glitchRing', 'haloCrownVoid'],
    ornament: ['glitchPixels', 'shardDust'],
    motion: ['flicker', 'rotateMedium'],
    abilityBias: { doubleTap: 1.1, tap: 1.0 },
    ruleBias: { mutationRateDelta: 1 },
  },
  {
    degree: 43,
    name: 'Void: Ink Veil',
    sigilFamily: ['inkLens', 'fractureCircle'],
    ornament: ['inkDrops', 'spectralDust'],
    motion: ['drift', 'pullIn'],
    abilityBias: { slowSwipe: 1.0, hold: 1.2 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 44,
    name: 'Void: Prism Warden',
    sigilFamily: ['prismSplit', 'metatronShard'],
    ornament: ['prismNoise', 'glitchPixels'],
    motion: ['shimmerSharp', 'flicker'],
    abilityBias: { twoFingerSwipe: 1.2, fastSwipe: 1.0 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 45,
    name: 'Void: Rift Gate',
    sigilFamily: ['riftLine', 'squareCircleVoid'],
    ornament: ['shardDust', 'cornerRunesVoid'],
    motion: ['tearOpen', 'steadyGlow'],
    abilityBias: { fastSwipe: 1.3 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 46,
    name: 'Void: Eclipse Eye',
    sigilFamily: ['eclipseLens', 'voidHole'],
    ornament: ['spectralDust', 'inkDrops'],
    motion: ['blinkVoid', 'pullIn'],
    abilityBias: { hold: 1.1, doubleTap: 1.1 },
    ruleBias: { mirrorThresholdDelta: 3 },
  },
  {
    degree: 47,
    name: 'Void: Spider Lattice',
    sigilFamily: ['fractureWeb', 'metatronShard'],
    ornament: ['webLines', 'glitchPixels'],
    motion: ['crawlShift', 'flicker'],
    abilityBias: { trace: 1.2, doubleTap: 1.0 },
    ruleBias: { mutationRateDelta: 2 },
  },
  {
    degree: 48,
    name: 'Void: Raven Sigil',
    sigilFamily: ['guardianMarkVoid', 'glitchRing'],
    ornament: ['featherShards', 'shardDust'],
    motion: ['shiver', 'snapDark'],
    abilityBias: { fastSwipe: 1.1, tap: 1.0 },
    ruleBias: { aestheticDriftDelta: 1 },
  },
  {
    degree: 49,
    name: 'Void: Metatron Shard',
    sigilFamily: ['metatronShard', 'fractureCircle'],
    ornament: ['shardDust', 'prismNoise'],
    motion: ['rotateSlow', 'fracturePulse'],
    abilityBias: { trace: 1.1, hold: 1.0 },
    ruleBias: { recursionStrengthDelta: 1 },
  },
  {
    degree: 50,
    name: 'Void: Null Choir',
    sigilFamily: ['voidHole', 'eclipseLens'],
    ornament: ['spectralDust', 'inkDrops'],
    motion: ['pullIn', 'silencePulse'],
    abilityBias: { rhythm: 1.2, hold: 1.0 },
    ruleBias: { mirrorThresholdDelta: 2 },
  },
  {
    degree: 51,
    name: 'Void: Fractal Bloom',
    sigilFamily: ['fractalEye', 'voidSpiral'],
    ornament: ['fractals', 'prismNoise'],
    motion: ['fractalGrow', 'flicker'],
    abilityBias: { trace: 1.3 },
    ruleBias: { mutationRateDelta: 3 },
  },
  {
    degree: 52,
    name: 'Void: Abyss Tide',
    sigilFamily: ['tideVoid', 'inkLens'],
    ornament: ['waveShards', 'inkDrops'],
    motion: ['wavePulse', 'pullIn'],
    abilityBias: { slowSwipe: 1.2, hold: 1.0 },
    ruleBias: { mirrorThresholdDelta: -1 },
  },
  {
    degree: 53,
    name: 'Void: Glitch Mirror',
    sigilFamily: ['glitchRing', 'mirrorLensVoid'],
    ornament: ['glitchPixels', 'spectralDust'],
    motion: ['mirrorShift', 'flicker'],
    abilityBias: { doubleTap: 1.2 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 54,
    name: 'Void: Rift Cartography',
    sigilFamily: ['riftLine', 'constellationVoid'],
    ornament: ['mapLines', 'shardDust'],
    motion: ['tearOpen', 'connectPulseVoid'],
    abilityBias: { fastSwipe: 1.2, trace: 1.0 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 55,
    name: 'Void: Serpent Coil',
    sigilFamily: ['voidSpiral', 'fractureWeb'],
    ornament: ['coilLines', 'inkDrops'],
    motion: ['spiralDrift', 'shiver'],
    abilityBias: { slowSwipe: 1.0, fastSwipe: 1.0 },
    ruleBias: { mutationRateDelta: 2 },
  },
  {
    degree: 56,
    name: 'Void: Prism Rain',
    sigilFamily: ['prismSplit', 'glitchRing'],
    ornament: ['prismNoise', 'shardDust'],
    motion: ['rainFall', 'flicker'],
    abilityBias: { tap: 1.0, doubleTap: 1.0 },
    ruleBias: { aestheticDriftDelta: 2 },
  },
  {
    degree: 57,
    name: 'Void: Shadow Archive',
    sigilFamily: ['squareCircleVoid', 'metatronShard'],
    ornament: ['cornerRunesVoid', 'mapLines'],
    motion: ['steadyGlow', 'pullIn'],
    abilityBias: { hold: 1.2, trace: 1.1 },
    ruleBias: { recursionStrengthDelta: 2 },
  },
  {
    degree: 58,
    name: 'Void: Eclipse Crown',
    sigilFamily: ['eclipseLens', 'haloCrownVoid'],
    ornament: ['spectralDust', 'glitchPixels'],
    motion: ['snapDark', 'flicker'],
    abilityBias: { doubleTap: 1.3 },
    ruleBias: { mirrorThresholdDelta: 3, mutationRateDelta: 1 },
  },
  {
    degree: 59,
    name: 'Void: Absolute Seal',
    sigilFamily: ['voidHole', 'fractureCircle'],
    ornament: ['inkDrops', 'shardDust'],
    motion: ['silencePulse', 'pullIn'],
    abilityBias: { hold: 1.3, fastSwipe: 1.0 },
    ruleBias: { mirrorThresholdDelta: 4, mutationRateDelta: 2 },
  },
];

export const DEGREE_TEMPLATES: DegreeTemplate[] = [
  ...SOLAR_DEGREES,
  ...LUNAR_DEGREES,
  ...VOID_DEGREES,
];
